theme = "blist"
languageCode = "en-US"
baseurl = "https://imrenagi.com"
title = "Imre Nagi"

[params]
  description = "Imre's Programming Notes."
  name = "Imre Nagi"

  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2024 - Imre Nagi · All rights reserved"
  favicon = "favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-200"

[params.homepage]
  title = "Halo! I'm Imre"
  description = "Software engineer and Google Developer Expert Cloud working on Infrastructure Engineering team in Goto Financial. I talk about cloud, infrastructure, programming, and sometimes politics."
  photo = "https://s3-us-west-2.amazonaws.com/anchor-generated-image-bank/production/podcast_uploaded_nologo400/1428780/1428780-1601846605001-8ec5cd464f826.jpg"

[params.homepage.social]
  description = "Follow my social media accounts!"
  twitter = "https://twitter.com/imrenagi"
  linkedin = "https://linkedin.com/in/imrenagi"
  github = "https://github.com/imrenagi"
  medium = "https://medium.com/@imrenagi"  

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Courses"
  url = "https://courses.imrenagi.com"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
